# Generated by Django 2.0.4 on 2018-05-09 21:51

# Librerias Standard
import datetime

# Librerias Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globales', '0001_initial'),
        ('oeu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(db_column='nombre_cargo', max_length=255)),
            ],
            options={
                'db_table': 'asuntos_laborales"."cargo',
                'verbose_name_plural': 'Cargos',
                'verbose_name': 'Cargo',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'asuntos_laborales"."categoria',
            },
        ),
        migrations.CreateModel(
            name='CondicionEgreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'asuntos_laborales"."condicion_egreso',
                'verbose_name_plural': 'Categorias',
                'verbose_name': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Dedicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dedicacion', models.CharField(db_column='nombre_dedicacion', max_length=255, verbose_name='Dedicación')),
                ('id_cargo', models.ForeignKey(db_column='id_cargo', on_delete=django.db.models.deletion.DO_NOTHING, to='asuntoslaborales.Cargo', verbose_name='Cargo')),
            ],
            options={
                'db_table': 'asuntos_laborales"."dedicacion',
                'verbose_name_plural': 'Dedicaciones',
                'verbose_name': 'Dedicación',
            },
        ),
        migrations.CreateModel(
            name='HistoriaLaboral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('fecha_egreso', models.DateField()),
                ('condicion_egreso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='asuntoslaborales.CondicionEgreso')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='oeu.Institucion')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='globales.Saime')),
            ],
            options={
                'db_table': 'asuntos_laborales"."historia_laboral',
                'verbose_name_plural': 'Historias Laborales',
                'verbose_name': 'Historia Laboral',
            },
        ),
        migrations.CreateModel(
            name='HlCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateField(blank=True, null=True)),
                ('grado', models.SmallIntegerField(blank=True, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='asuntoslaborales.Categoria')),
                ('historia_laboral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='asuntoslaborales.HistoriaLaboral')),
            ],
            options={
                'db_table': 'asuntos_laborales"."hl_categoria',
                'verbose_name_plural': 'Categorias de la Historia Laboral',
                'verbose_name': 'Categoria de la Historia Laboral',
            },
        ),
        migrations.CreateModel(
            name='HlDedicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateField(blank=True, null=True)),
                ('dedicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='asuntoslaborales.Dedicacion')),
                ('historia_laboral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='asuntoslaborales.HistoriaLaboral')),
            ],
            options={
                'db_table': 'asuntos_laborales"."hl_dedicacion',
                'verbose_name_plural': 'Dedicaciones de la Historia Laboral',
                'verbose_name': 'Dedicación de la Historia Laboral',
            },
        ),
        migrations.CreateModel(
            name='HlDesembolso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('monto', models.FloatField(blank=True, null=True)),
                ('historia_laboral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='asuntoslaborales.HistoriaLaboral')),
            ],
            options={
                'db_table': 'asuntos_laborales"."hl_desembolso',
                'ordering': ['fecha'],
                'verbose_name_plural': 'Desembolsos de Prestaciones Sociales de la Historia Laboral',
                'verbose_name': 'Desembolso de Prestaciones Sociales de la Historia Laboral',
            },
        ),
        migrations.CreateModel(
            name='HlPermiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('descuenta', models.NullBooleanField(default=False)),
                ('historia_laboral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='asuntoslaborales.HistoriaLaboral')),
            ],
            options={
                'db_table': 'asuntos_laborales"."hl_permiso',
                'verbose_name_plural': 'Permisos de la Historia Laboral',
                'verbose_name': 'Permiso de la Historia Laboral',
            },
        ),
        migrations.CreateModel(
            name='HlSalarioIntegralAnual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField(blank=True, null=True)),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('sueldo', models.FloatField(blank=True, null=True)),
                ('antiguedad', models.SmallIntegerField(blank=True, null=True)),
                ('historia_laboral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='asuntoslaborales.HistoriaLaboral')),
            ],
            options={
                'db_table': 'asuntos_laborales"."hl_salario_integral_anual',
                'verbose_name_plural': 'Salarios Integrales Anuales de la Historia Laboral',
                'verbose_name': 'Salario Integral Anual de la Historia Laboral',
            },
        ),
        migrations.CreateModel(
            name='Prima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prima', models.CharField(db_column='nombre_prima', max_length=255, verbose_name='Prima')),
                ('desde', models.DateField(db_column='desde', verbose_name='Desde')),
                ('hasta', models.DateField(db_column='hasta', verbose_name='Hasta')),
                ('monto_prima', models.DecimalField(db_column='monto_prima', decimal_places=2, max_digits=8, verbose_name='Monto Prima')),
                ('cargo', models.ForeignKey(db_column='id_cargo', on_delete=django.db.models.deletion.DO_NOTHING, to='asuntoslaborales.Cargo', verbose_name='Cargo')),
                ('dedicacion', models.ForeignKey(db_column='id_dedicacion', on_delete=django.db.models.deletion.DO_NOTHING, to='asuntoslaborales.Dedicacion', verbose_name='Dedicación')),
                ('id_institucion', models.ForeignKey(db_column='id_institucion', on_delete=django.db.models.deletion.DO_NOTHING, to='oeu.Institucion', verbose_name='Institución')),
                ('id_tipo_institucion', models.ForeignKey(blank=True, db_column='id_tipo_institucion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipoInstitucion4', to='oeu.TipoInstitucion', verbose_name='Tipo IEU')),
                ('id_tipo_institucion_detalle', models.ForeignKey(db_column='id_tipo_institucion_detalle', on_delete=django.db.models.deletion.DO_NOTHING, to='oeu.TipoInstitucionDetalle', verbose_name='Tipo IEU Detalle')),
                ('id_tipo_institucion_especifico', models.ForeignKey(db_column='id_tipo_institucion_especifico', on_delete=django.db.models.deletion.DO_NOTHING, to='oeu.TipoInstitucionEspecifico', verbose_name='Tipo IEU Especifico')),
            ],
            options={
                'db_table': 'asuntos_laborales"."prima',
                'verbose_name_plural': 'Primas',
                'verbose_name': 'Prima',
            },
        ),
        migrations.CreateModel(
            name='SoporteFormal',
            fields=[
                ('id_sf', models.AutoField(db_column='id_soporte_formal', primary_key=True, serialize=False)),
                ('descripcion_sf', models.CharField(db_column='descripcion_soporte_formal', max_length=255, verbose_name='Descripción SF')),
                ('fecha_sf', models.DateField(db_column='fecha_soporte_formal', verbose_name='Fecha SF')),
                ('numero_sf', models.CharField(blank=True, db_column='numero_soporte_formal', max_length=255, null=True, verbose_name='Número SF')),
                ('numero_gaceta', models.CharField(blank=True, max_length=45, null=True, verbose_name='Gaceta SF')),
                ('fecha_gaceta', models.DateField(blank=True, null=True, verbose_name='Fecha Gaceta SF')),
                ('creado', models.DateTimeField(blank=True, null=True)),
                ('actualizado', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
            options={
                'db_table': 'asuntos_laborales"."soporte_formal',
                'verbose_name_plural': 'Soportes Formales',
                'verbose_name': 'Soporte Formal',
            },
        ),
        migrations.CreateModel(
            name='SueldoBasico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.DateField(db_column='desde', verbose_name='Desde')),
                ('hasta', models.DateField(db_column='hasta', verbose_name='Hasta')),
                ('sueldo', models.DecimalField(db_column='sueldo', decimal_places=2, max_digits=8, verbose_name='Sueldo')),
                ('cargo', models.ForeignKey(db_column='id_cargo', on_delete=django.db.models.deletion.DO_NOTHING, to='asuntoslaborales.Cargo', verbose_name='Cargo')),
                ('dedicacion', models.ForeignKey(db_column='id_dedicacion', on_delete=django.db.models.deletion.DO_NOTHING, to='asuntoslaborales.Dedicacion', verbose_name='Dedicación')),
                ('id_institucion', models.ForeignKey(db_column='id_institucion', on_delete=django.db.models.deletion.DO_NOTHING, to='oeu.Institucion', verbose_name='Institución')),
                ('id_tipo_institucion', models.ForeignKey(blank=True, db_column='id_tipo_institucion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipoInstitucion3', to='oeu.TipoInstitucion', verbose_name='Tipo IEU')),
                ('id_tipo_institucion_detalle', models.ForeignKey(db_column='id_tipo_institucion_detalle', on_delete=django.db.models.deletion.DO_NOTHING, to='oeu.TipoInstitucionDetalle', verbose_name='Tipo IEU Detalle')),
                ('id_tipo_institucion_especifico', models.ForeignKey(db_column='id_tipo_institucion_especifico', on_delete=django.db.models.deletion.DO_NOTHING, to='oeu.TipoInstitucionEspecifico', verbose_name='Tipo IEU Especifico')),
            ],
            options={
                'db_table': 'asuntos_laborales"."sueldo_basico',
                'verbose_name_plural': 'Sueldos Básicos',
                'verbose_name': 'Sueldo Básico',
            },
        ),
        migrations.CreateModel(
            name='TasaInteres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateTimeField(blank=True, null=True)),
                ('fecha_hasta', models.DateTimeField(blank=True, null=True)),
                ('tasa_pasiva', models.FloatField(blank=True, null=True)),
                ('tasa_promedio', models.FloatField(blank=True, null=True)),
                ('tasa_activa', models.FloatField(blank=True, null=True)),
                ('tasa_90_dias', models.FloatField(blank=True, null=True)),
                ('interest_rate', models.FloatField(blank=True, null=True)),
                ('stage_type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asuntos_laborales"."tasa_interes',
            },
        ),
        migrations.CreateModel(
            name='TipoCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=255)),
                ('iniciales', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'asuntos_laborales"."tipo_categoria',
            },
        ),
        migrations.CreateModel(
            name='TipoDesembolso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'asuntos_laborales"."tipo_desembolso',
            },
        ),
        migrations.CreateModel(
            name='TipoPermiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'asuntos_laborales"."tipo_permiso',
            },
        ),
        migrations.CreateModel(
            name='TipoPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_personal', models.CharField(db_column='nombre_tipo_personal', max_length=255, verbose_name='Tipo Personal')),
            ],
            options={
                'db_table': 'asuntos_laborales"."tipo_personal',
                'verbose_name_plural': 'Tipos de Personal',
                'verbose_name': 'Tipo de Personal',
            },
        ),
        migrations.CreateModel(
            name='TipoSoporteFormal',
            fields=[
                ('id_tipo_sf', models.AutoField(db_column='id_tipo_soporte_formal', primary_key=True, serialize=False)),
                ('nombre_tipo_sf', models.CharField(db_column='nombre_tipo_soporte_formal', max_length=255)),
            ],
            options={
                'db_table': 'asuntos_laborales"."tipo_sf',
                'verbose_name_plural': 'Tipos SF',
                'verbose_name': 'Tipo SF',
            },
        ),
        migrations.AddField(
            model_name='sueldobasico',
            name='id_tipo_personal',
            field=models.ForeignKey(db_column='id_tipo_personal', on_delete=django.db.models.deletion.DO_NOTHING, to='asuntoslaborales.TipoPersonal', verbose_name='Tipo Personal'),
        ),
        migrations.AddField(
            model_name='sueldobasico',
            name='sf',
            field=models.ManyToManyField(blank=True, db_column='id_soporte_formal', db_table='asuntos_laborales"."sueldo_sf', to='asuntoslaborales.SoporteFormal', verbose_name='Soporte Formal'),
        ),
        migrations.AddField(
            model_name='soporteformal',
            name='id_tipo_sf',
            field=models.ForeignKey(blank=True, db_column='id_tipo_soporte_formal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='asuntoslaborales.TipoSoporteFormal', verbose_name='Tipo SF'),
        ),
        migrations.AddField(
            model_name='prima',
            name='id_tipo_personal',
            field=models.ForeignKey(db_column='id_tipo_personal', on_delete=django.db.models.deletion.DO_NOTHING, to='asuntoslaborales.TipoPersonal', verbose_name='Tipo Personal'),
        ),
        migrations.AddField(
            model_name='hlpermiso',
            name='tipo_permiso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='asuntoslaborales.TipoPermiso'),
        ),
        migrations.AddField(
            model_name='hldesembolso',
            name='tipo_desembolso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='asuntoslaborales.TipoDesembolso'),
        ),
        migrations.AddField(
            model_name='historialaboral',
            name='tipo_personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='asuntoslaborales.TipoPersonal'),
        ),
        migrations.AddField(
            model_name='dedicacion',
            name='id_tipo_personal',
            field=models.ForeignKey(db_column='id_tipo_personal', on_delete=django.db.models.deletion.DO_NOTHING, to='asuntoslaborales.TipoPersonal', verbose_name='Tipo Personal'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='id_tipo_personal',
            field=models.ForeignKey(db_column='id_tipo_personal', on_delete=django.db.models.deletion.DO_NOTHING, to='asuntoslaborales.TipoPersonal', verbose_name='Tipo Personal'),
        ),
    ]
