# Generated by Django 2.0.6 on 2018-06-21 16:04

# Librerias Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asuntoslaborales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prima',
            name='id_tipo_institucion_especifico',
            field=models.ForeignKey(db_column='id_tipo_institucion_especifico', on_delete=django.db.models.deletion.DO_NOTHING, to='oeu.SubTipoInstitucion', verbose_name='Sub Tipo Institucion'),
        ),
        migrations.AlterField(
            model_name='sueldobasico',
            name='id_tipo_institucion_especifico',
            field=models.ForeignKey(db_column='id_tipo_institucion_especifico', on_delete=django.db.models.deletion.DO_NOTHING, to='oeu.SubTipoInstitucion', verbose_name='Sub Tipo Institucion'),
        ),
    ]
