# Generated by Django 2.1.4 on 2018-12-11 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('globales', '0003_autoridadesinstitucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaClinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rif', models.CharField(db_column='rif_auditoria', max_length=30, verbose_name='rif de la clinica en auditoria')),
                ('nombre', models.CharField(db_column='nombre_auditoria', max_length=255, verbose_name='nombre de la clinica en auditoria')),
                ('direccion', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='fecha de los cambios')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='globales.Estado', verbose_name='estado de la clincia en auditoria')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='globales.Municipio', verbose_name='municipio de la clinica en auditoria')),
                ('parroquia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='globales.Parroquia', verbose_name='parroquia de la clinica en auditoria')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsable de los cambios')),
            ],
            options={
                'verbose_name_plural': 'Auditorias a las clinicas',
                'db_table': 'sismeu"."auditoria_clinica',
                'verbose_name': 'Auditoria a la clinica',
            },
        ),
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rif', models.CharField(db_column='rif', max_length=13, unique=True, verbose_name='rif de la clinica')),
                ('nombre', models.CharField(db_column='nombre', max_length=255, verbose_name='nombre de la clinica')),
                ('direccion', models.TextField()),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Editor de la clínica')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='globales.Estado', verbose_name='estado de la clinica')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='globales.Municipio', verbose_name='municipio de la clinica')),
                ('parroquia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='globales.Parroquia', verbose_name='parroquia de la clinica')),
            ],
            options={
                'verbose_name_plural': 'Clinicas',
                'db_table': 'sismeu"."clinica',
                'verbose_name': 'Clinica',
            },
        ),
        migrations.CreateModel(
            name='ConvenioClinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sismeu.Clinica', verbose_name='Clínica del convenio')),
            ],
            options={
                'verbose_name_plural': 'Convenios con la clínica',
                'db_table': 'sismeu"."convenio_clinica',
                'verbose_name': 'Convenio con la clínica',
            },
        ),
        migrations.CreateModel(
            name='Convenios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=30, verbose_name='Nombre del convenio')),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Convenios de la clínica',
                'db_table': 'sismeu"."convenios',
                'verbose_name': 'Convenio con la clínica',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Departamentos de la clínica',
                'db_table': 'sismeu"."departamento',
                'verbose_name': 'Departamento de la clínica',
            },
        ),
        migrations.CreateModel(
            name='HistoricoClinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_activacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de activacion de la clinica')),
                ('fecha_inactivacion', models.DateField(null=True, verbose_name='fecha de inactivacion de la clinica')),
                ('clinica', models.ForeignKey(db_column='clinica_id', on_delete=django.db.models.deletion.PROTECT, to='sismeu.Clinica', verbose_name='Clinica')),
            ],
            options={
                'db_table': 'sismeu"."historico_clinica',
                'verbose_name': 'Historicos de las clinicas',
            },
        ),
        migrations.CreateModel(
            name='MotivoInactivacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Motivos de inactivacion',
                'db_table': 'sismeu"."motivo_inactivacion',
                'verbose_name': 'Motivo de inactivacion',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=255, verbose_name='Nombre de la Región')),
            ],
            options={
                'verbose_name_plural': 'Regiones',
                'db_table': 'sismeu"."region',
                'verbose_name': 'Region',
            },
        ),
        migrations.CreateModel(
            name='RegionEstado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='globales.Estado')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sismeu.Region')),
            ],
            options={
                'db_table': 'sismeu"."region_estado',
            },
        ),
        migrations.CreateModel(
            name='ResponsableRegional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sismeu.Region')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sismeu"."responsable_region',
            },
        ),
        migrations.CreateModel(
            name='TelefonoClinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(db_column='telefono', max_length=30, verbose_name='Telefono de la clinica')),
                ('publicar', models.BooleanField(default=False)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sismeu.Clinica', verbose_name='Clinica a contactar')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sismeu.Departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name_plural': 'Telefonos de la clínica',
                'db_table': 'sismeu"."telefono_clinica',
                'verbose_name': 'Telefono de la clínica',
            },
        ),
        migrations.AddField(
            model_name='region',
            name='estado',
            field=models.ManyToManyField(related_name='estado_region', through='sismeu.RegionEstado', to='globales.Estado', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='region',
            name='responsable',
            field=models.ManyToManyField(related_name='responsable', through='sismeu.ResponsableRegional', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicoclinica',
            name='motivo_inactivacion',
            field=models.ForeignKey(db_column='motivo_inactivacion_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='motivo_inactivacion_id', to='sismeu.MotivoInactivacion', verbose_name='Motivo para inactivar la clinica'),
        ),
        migrations.AddField(
            model_name='historicoclinica',
            name='responsable_activacion',
            field=models.ForeignKey(db_column='responsable_activacion', on_delete=django.db.models.deletion.DO_NOTHING, related_name='reponsable_regional_id', to=settings.AUTH_USER_MODEL, verbose_name='responsable de la activacion de la clinica'),
        ),
        migrations.AddField(
            model_name='historicoclinica',
            name='responsable_inactivacion',
            field=models.ForeignKey(db_column='responsable_inactivacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsable_regional_id', to=settings.AUTH_USER_MODEL, verbose_name='responsable de la inactivacion de la clinica'),
        ),
        migrations.AddField(
            model_name='convenioclinica',
            name='convenio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sismeu.Convenios', verbose_name='Convenio con la clínica'),
        ),
    ]
