# Django Library
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
from django.apps import AppConfig


class GlobalesConfig(AppConfig):
    name = 'globales'
