# Generated by Django 2.1.2 on 2018-11-14 17:11

from django.db import migrations, models
import django.db.models.deletion
import globales.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('letra_cedula_identidad', models.CharField(max_length=1)),
                ('cedula_identidad', models.IntegerField(unique=True)),
                ('rif', models.CharField(blank=True, max_length=255, null=True)),
                ('otros_nombres', models.CharField(blank=True, max_length=255, null=True)),
                ('otros_apellidos', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('celular', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('pasaporte', models.CharField(blank=True, max_length=255, null=True)),
                ('foto', models.CharField(blank=True, max_length=100, null=True)),
                ('cne', models.CharField(blank=True, max_length=255, null=True)),
                ('correo_secundario', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'saime',
            },
        ),
        migrations.CreateModel(
            name='CorreoInstitucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=255)),
            ],
            options={
                'verbose_name': 'Correo Institución',
                'db_table': 'correo_institucion',
                'verbose_name_plural': 'Correos Institución',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_estado_ine', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='Etnia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'etnia',
            },
        ),
        migrations.CreateModel(
            name='InstitucionMinisterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('siglas', models.CharField(max_length=50)),
                ('rif', models.CharField(max_length=45)),
                ('dep_admin', models.CharField(choices=[('PÚBLICA', 'PÚBLICA'), ('PRIVADA', 'PRIVADA')], max_length=7)),
                ('tipo_institucion', models.CharField(choices=[('IEU', 'INSTITUCIÓN DE EDUCACIÓN UNIVERSITARIA'), ('ENTE ADSCRITO', 'ENTE ADSCRITO'), ('OTRO', 'OTRO')], max_length=37)),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Ente Adscrito',
                'db_table': 'institucion_ministerial',
                'verbose_name_plural': 'Entes Adscritos',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_municipio_completo_ine', models.CharField(max_length=4)),
                ('id_estado_ine', models.CharField(max_length=2, verbose_name=globales.models.Estado)),
                ('id_municipio_ine', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='globales.Estado')),
            ],
            options={
                'db_table': 'municipio',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_iso', models.CharField(blank=True, max_length=3, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_iso', models.CharField(blank=True, max_length=255, null=True)),
                ('alfa2', models.CharField(blank=True, max_length=2, null=True)),
                ('alfa3', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'pais',
            },
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_parroquia_completo_ine', models.CharField(max_length=6)),
                ('id_municipio_completo_ine', models.CharField(max_length=4)),
                ('id_estado_ine', models.CharField(max_length=2)),
                ('id_municipio_ine', models.CharField(max_length=2)),
                ('id_parroquia_ine', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=255)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='globales.Municipio')),
            ],
            options={
                'db_table': 'parroquia',
            },
        ),
    ]
