# Generated by Django 2.1.2 on 2018-11-14 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globales', '0001_initial'),
        ('oeu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='correoinstitucion',
            name='instancia_administrativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.InstanciaAdministrativa'),
        ),
        migrations.AddField(
            model_name='correoinstitucion',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='globales.InstitucionMinisterial'),
        ),
    ]
