# -*- coding: utf-8 -*-
"""
Django settings for opsu project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/

SELECT reltuples::BIGINT AS estimate FROM pg_class WHERE relname='table_name';

"""

# Librerias Standard
# Standard Library
import os

# Librerias desarrolladas por mi
from opsu.secret import *

GETTEXT = lambda s: s

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


GOOGLE_RECAPTCHA_SECRET_KEY = '6LevF1gUAAAAAPn3z8EswCgIk1S_jLKYdf4s62B9'

PASSWORD_RESET_TIMEOUT_DAYS = 2

AUTH_USER_MODEL = 'cuenta.Persona'

######################## ENVIO DE CORREO EN PRODUCCIÓN ########################
EMAIL_HOST = 'correo.opsu.gob.ve'
EMAIL_PORT = 25
EMAIL_HOST_USER = 'no-responder'
EMAIL_HOST_PASSWORD = 'CorreoNoResponder4874@'
EMAIL_USE_TLS = True

######################## ENVIO DE CORREO EN DESARROLLO ########################


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    # mis aplicaciones #
    'grado',
    # 'asuntoslaborales',
    'globales',
    'oeuacademic',
    'oeuconfig',
    'oeu',
    'cuenta',
    'sismeu',
    'snipni',
    ####################
    'dal',
    'dal_select2',
    'suit',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'leaflet',
    'djgeojson',
    # 'django.contrib.sites',
    # 'debug_toolbar',
]


SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'opsu.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.jinja2.Jinja2',
        'DIRS': [os.path.join(BASE_DIR, 'jinja2')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': ['django_settings_export.settings_export',],
            'environment': 'opsu.jinja2.environment'
        },
    },
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.template.context_processors.csrf',
                'django.template.context_processors.tz',
                'django.template.context_processors.static',
            ],
        },
    },
]


NOMBRE_APP = 'MPPEUCT|OPSU'
ESLOGAN = 'Software de gestión para Fincas'
PREFIJO = 'MPPEUCT'
SUFIJO = 'OPSU'
VERSION = '1.0'
INICIAL_A = 'E'
INICIAL_B = 'U'

SETTINGS_EXPORT = [
    'NOMBRE_APP',
    'ESLOGAN',
    'PREFIJO',
    'SUFIJO',
    'VERSION',
    'INICIAL_A',
    'INICIAL_B'
]


LEAFLET_CONFIG = {
    'DEFAULT_CENTER': (50.387507803003146, 30.454101562499996),
    'DEFAULT_ZOOM': 10,
    'MIN_ZOOM': 3,
    'MAX_ZOOM': 18,
    'TILES': [],
    'OVERLAYS': [],

    'PLUGINS': {
        'markercluster': {
            'css': ['css/MarkerCluster.Default.css', 'css/MarkerCluster.css'],
            'js': 'js/leaflet.markercluster.js',
            'auto-include': True
        }
    }
}

SITE_ID = 1

WSGI_APPLICATION = 'opsu.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.UnsaltedMD5PasswordHasher',
]

LOGIN_URL = 'cuenta:login'
LOGIN_REDIRECT_URL = 'cuenta:perfil'


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Caracas'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# LANGUAGES = [
#     ('es', 'Español'),
# ]

LANGUAGES = (
    ## Customize this
    ('es', GETTEXT('es')),
)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

MEDIA_URL = '/media/'

MEDIA_ROOT = 'media'

STATIC_URL = '/static/'

STATIC_ROOT = 'static'


STATICFILES_DIRS = [
    "/home/special.polls.com/polls/static",
    "/home/polls.com/polls/static",
    "/opt/webfiles/common",
]

SUIT_CONFIG = {
    # header
    'ADMIN_NAME': 'OPSU',
    'HEADER_DATE_FORMAT': 'l, j. F Y',
    'HEADER_TIME_FORMAT': 'H:i',

    # forms
    'SHOW_REQUIRED_ASTERISK': True,  # Default True
    # 'CONFIRM_UNSAVED_CHANGES': True,  # Default True

    # 'MENU_OPEN_FIRST_CHILD': False,

    # menu
    # 'SEARCH_URL': '/admin/auth/user/',
    # 'MENU_ICONS': {
    #     'sites': 'icon-leaf',
    #     'auth': 'icon-lock',
    # },
    # 'MENU_OPEN_FIRST_CHILD': True, # Default True
    # 'MENU_EXCLUDE': ('demografia.miembrohogar',),

    'MENU': (
        {
            'label': 'Personas y Grupos',
            'icon': 'icon-user',
            'models': (
                'cuenta.Persona',
                'auth.group',
                'admin.LogEntry'
            )
        },
        {'label': 'Translations', 'icon':'icon-globe', 'url': '/admin/translate/'},
        # 'sites',
        # 'Asuntoslaborales',
        {'app': 'asuntoslaborales', 'label': 'Asuntos Laborales', 'icon':'icon-wrench'},
        {'app': 'visitas', 'label': 'Visitas', 'icon':'icon-wrench'},
        {'app': 'demografia', 'label': 'Demografía', 'icon':'icon-map-marker'},
        {'app': 'grado', 'label': 'Actos de grado', 'icon':'icon-map-marker'},
        {'app': 'sismeu', 'label': 'Sismeu', 'icon':'icon-map-marker'},
        {
            'app': 'oeu',
            'label': 'OEU Instituciones',
            'icon':'icon-book',
            'models': (
                ############# Instituciones #############
                'Institucion',
                'TipoInstitucion',
                'SubTipoInstitucion',
                'TipoInstitucionDetalle',
                'DependenciaAdministrativa',
                'Localidad',
                'AyudaEconomica',
                'ActividadCultural',
                'DisciplinaDeportiva',
                'OrganizacionEstudiantil',
                'AgrupacionCivica',
                'RedSocial',
                'TipoLocalidad',
                'InstanciaAdministrativa',
                'RequisitoIngreso',
                ######## Soporte Formal de Cambio #######
                'SoporteFormalCambio',
                'TipoSoporteFormalCambio',
                'globales.Archivo',
                ################# Otros #################
                'Turno'
            )
        },
        {
            'app': 'oeu',
            'label': 'OEU Prog. Académicos',
            'icon':'icon-book',
            'models': (
                'Carrera',
                'TipoCarrera',
                'AreaConocimiento',
                'SubAreaConocimiento',
                'Modalidad',
                'Titulo',
                'Servicio',
            )
        },
    ),

    # misc
    'LIST_PER_PAGE': 15
}


USE_DJANGO_JQUERY = False
JQUERY_URL = False
