# Generated by Django 2.0.6 on 2018-07-10 12:52

# Librerias Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activacion',
            fields=[
                ('cod_activacion', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('interpretacion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'oeu"."activacion',
            },
        ),
        migrations.CreateModel(
            name='ActividadCultural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'oeu"."actividad_cultural',
                'verbose_name_plural': 'Actividades Culturales',
                'verbose_name': 'Actividad Cultural',
            },
        ),
        migrations.CreateModel(
            name='AgrupacionCivica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'oeu"."agrupacion_civica',
                'verbose_name_plural': 'Agrupaciones Civicas',
                'verbose_name': 'Agrupación Civica',
            },
        ),
        migrations.CreateModel(
            name='AyudaEconomica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'ordering': ['nombre'],
                'db_table': 'oeu"."tipo_ayuda_economica',
                'verbose_name_plural': 'Ayudas Económicas',
                'verbose_name': 'Ayuda Económica',
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id_bitacora', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tabla', models.CharField(max_length=64)),
                ('datos_registro', models.TextField()),
                ('fecha_hora_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'oeu"."bitacora',
            },
        ),
        migrations.CreateModel(
            name='DependenciaAdministrativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'oeu"."dependencia_administrativa',
                'verbose_name_plural': 'Dependencias Administrativas',
                'verbose_name': 'Dependencia Administrativa',
            },
        ),
        migrations.CreateModel(
            name='DisciplinaDeportiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'oeu"."disciplina_deportiva',
                'verbose_name_plural': 'Disciplinas Deportivas',
                'verbose_name': 'Disciplina Deportiva',
            },
        ),
        migrations.CreateModel(
            name='InstanciaAdministrativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('publicar', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['nombre'],
                'db_table': 'oeu"."instancia_administrativa',
                'verbose_name_plural': 'Instancias Administrativas',
                'verbose_name': 'Instancia Administrativa',
            },
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'ordering': ['nombre'],
                'db_table': 'oeu"."modalidad',
                'verbose_name_plural': 'Regímenes de Estudio',
                'verbose_name': 'Régimen de Estudio',
            },
        ),
        migrations.CreateModel(
            name='OrganizacionEstudiantil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'oeu"."organizacion_estudiantil',
                'verbose_name_plural': 'Organizaciones Estudiantiles',
                'verbose_name': 'Organizacion Estudiantil',
            },
        ),
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'oeu"."red_social',
                'verbose_name_plural': 'Redes Sociales',
                'verbose_name': 'Red Social',
            },
        ),
        migrations.CreateModel(
            name='RequisitoIngreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oeu"."requisito_ingreso',
                'verbose_name_plural': 'Requisitos de Ingreso',
                'verbose_name': 'Requisito de Ingreso',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oeu"."servicio',
                'verbose_name_plural': 'Servicios',
                'verbose_name': 'Servicio',
            },
        ),
        migrations.CreateModel(
            name='SoporteFormalCambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=255)),
                ('numero_gaceta', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha_gaceta', models.DateField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'oeu"."soporte_formal_cambio',
                'verbose_name_plural': 'Soportes Formales de Cambio',
                'verbose_name': 'Soporte Formal de Cambio',
            },
        ),
        migrations.CreateModel(
            name='TipoCarrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oeu"."tipo_carrera',
                'verbose_name_plural': 'Tipos de Programa Académico',
                'verbose_name': 'Tipo de Programa Académico',
            },
        ),
        migrations.CreateModel(
            name='TipoLocalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oeu"."tipo_localidad',
                'verbose_name_plural': 'Tipos de localidad',
                'verbose_name': 'Tipo de localidad',
            },
        ),
        migrations.CreateModel(
            name='TipoSoporteFormalCambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'oeu"."tipo_sfc',
                'verbose_name_plural': 'Tipos SFC',
                'verbose_name': 'Tipo SFC',
            },
        ),
        migrations.CreateModel(
            name='TipoTurnoDeEstudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'oeu"."turno',
                'verbose_name_plural': 'Turnos de Estudio',
                'verbose_name': 'Turno de Estudio',
            },
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
            options={
                'ordering': ['nombre'],
                'db_table': 'oeu"."titulo',
                'verbose_name_plural': 'Títulos',
                'verbose_name': 'Título',
            },
        ),
        migrations.AddField(
            model_name='soporteformalcambio',
            name='tipo_sfc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeuconfig.TipoSoporteFormalCambio'),
        ),
    ]
