# Generated by Django 2.0.5 on 2018-07-13 15:10

# Librerias Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oeuconfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soporteformalcambio',
            name='documento_legal',
            field=models.FileField(blank=True, null=True, upload_to='documento_legal/'),
        ),
    ]
