# Generated by Django 2.0.5 on 2018-07-13 15:16

# Librerias Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oeuconfig', '0002_soporteformalcambio_documento_legal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soporteformalcambio',
            name='documento_legal',
        ),
    ]
