# Generated by Django 2.0.5 on 2018-07-13 15:18

# Librerias Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oeuconfig', '0003_remove_soporteformalcambio_documento_legal'),
    ]

    operations = [
        migrations.AddField(
            model_name='soporteformalcambio',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='archivo_adjunto/'),
        ),
    ]
