# Generated by Django 2.0.5 on 2018-07-16 12:25

# Librerias Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oeuconfig', '0004_soporteformalcambio_archivo_adjunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soporteformalcambio',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='archivo_adjunto_sfc/'),
        ),
    ]
