# Django Library
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
# Librerias Django
from django.apps import AppConfig


class AsuntoslaboralesConfig(AppConfig):
    name = 'asuntoslaborales'
