# Generated by Django 2.1.4 on 2018-12-11 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globales', '0003_autoridadesinstitucion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguidorEstadal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.ManyToManyField(related_name='estado_seguidor', to='globales.Estado', verbose_name='Estados a dar seguimiento')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Seguidor de estados')),
            ],
            options={
                'db_table': 'pni"."seguidor_estadal',
                'verbose_name': 'Seguidor Estadal',
                'verbose_name_plural': 'Seguidores Estadales',
            },
        ),
    ]
