# Generated by Django 2.1.2 on 2018-11-14 17:11

import cuenta.libSobreEscribirImagen
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djgeojson.fields
import oeu.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oeuconfig', '0005_auto_20180716_0825'),
        ('globales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadCultural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Actividad Cultural',
                'db_table': 'oeu"."actividad_cultural',
                'verbose_name_plural': 'Actividades Culturales',
            },
        ),
        migrations.CreateModel(
            name='ActividadCulturalLocalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telefono', models.CharField(max_length=19)),
                ('id_actividad_cultural', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.ActividadCultural')),
            ],
            options={
                'verbose_name': 'Actividad Cultural',
                'db_table': 'oeu"."actividad_cultural_localidad',
                'verbose_name_plural': 'Actividades Culturales',
            },
        ),
        migrations.CreateModel(
            name='AgrupacionCivica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Agrupación Civica',
                'db_table': 'oeu"."agrupacion_civica',
                'verbose_name_plural': 'Agrupaciones Civicas',
            },
        ),
        migrations.CreateModel(
            name='AgrupacionCivicaLocalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telefono', models.CharField(max_length=19)),
                ('agrupacion_civica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.AgrupacionCivica')),
            ],
            options={
                'verbose_name': 'Agrupación Civica',
                'db_table': 'oeu"."agrupacion_civica_localidad',
                'verbose_name_plural': 'Agrupaciones Civicas',
            },
        ),
        migrations.CreateModel(
            name='AreaConocimiento',
            fields=[
                ('id_area_conocimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_area_conocimiento', models.CharField(max_length=100, verbose_name='Área de Conocimiento')),
                ('descripcion', models.TextField()),
            ],
            options={
                'ordering': ['nombre_area_conocimiento'],
                'verbose_name': 'Área de Conocimiento',
                'db_table': 'oeu"."area_conocimiento',
                'verbose_name_plural': 'Áreas de Conocimiento',
            },
        ),
        migrations.CreateModel(
            name='AyudaEconomica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Ayuda Económica',
                'db_table': 'oeu"."tipo_ayuda_economica',
                'verbose_name_plural': 'Ayudas Económicas',
            },
        ),
        migrations.CreateModel(
            name='AyudaEconomicaLocalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telefono', models.CharField(max_length=19)),
                ('ayuda_economica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.AyudaEconomica')),
            ],
            options={
                'verbose_name': 'Ayuda Económica',
                'db_table': 'oeu"."tipo_ayuda_economica_localidad',
                'verbose_name_plural': 'Ayudas Económicas',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('mercado_ocupacional', models.TextField(blank=True, null=True)),
                ('duracion', models.SmallIntegerField(blank=True, null=True)),
                ('prioritaria', models.BooleanField(default=False)),
                ('nombre_edit', models.CharField(max_length=255)),
                ('descripcion_edit', models.TextField()),
                ('mercado_ocupacional_edit', models.TextField()),
                ('duracion_edit', models.SmallIntegerField()),
                ('prioritaria_edit', models.BooleanField(default=False)),
                ('publicar', models.BooleanField(default=False)),
                ('cod_activacion', models.CharField(blank=True, max_length=9, null=True)),
                ('area_conocimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='AreaConocimiento2', to='oeu.AreaConocimiento')),
                ('area_conocimiento_edit', models.ForeignKey(db_column='area_conocimiento_edit', on_delete=django.db.models.deletion.PROTECT, to='oeu.AreaConocimiento')),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Programa Académico',
                'db_table': 'oeu"."carrera',
                'verbose_name_plural': 'Programas Académicos',
            },
        ),
        migrations.CreateModel(
            name='CarreraGrupoCarrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.Carrera')),
            ],
            options={
                'db_table': 'oeu"."carrera_grupo_carrera',
            },
        ),
        migrations.CreateModel(
            name='CarreraGrupoRamaEducaion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.Carrera')),
            ],
            options={
                'db_table': 'oeu"."carrera_grupo_rama_educaion',
            },
        ),
        migrations.CreateModel(
            name='CineFCampoAmplio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cine_f_campo_amplio', models.CharField(max_length=2)),
                ('descripcion_campo_amplio', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'CINE Campo Amplio',
                'db_table': 'oeu"."cine_campo_amplio',
                'verbose_name_plural': 'CINE Campos Amplios',
            },
        ),
        migrations.CreateModel(
            name='CineFCampoDetallado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cine_f_campo_detallado', models.CharField(max_length=4)),
                ('descripcion_campo_detallado', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'CINE Campo Detallado',
                'db_table': 'oeu"."cine_campo_detallado',
                'verbose_name_plural': 'CINE Campos Detallados',
            },
        ),
        migrations.CreateModel(
            name='CineFCampoEspecifico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cine_f_campo_especifico', models.CharField(max_length=3)),
                ('descripcion_campo_especifico', models.CharField(max_length=255)),
                ('id_cine_f_campo_amplio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.CineFCampoAmplio')),
            ],
            options={
                'verbose_name': 'CINE Campo Especifico',
                'db_table': 'oeu"."cine_campo_especifico',
                'verbose_name_plural': 'CINE Campos Especificos',
            },
        ),
        migrations.CreateModel(
            name='CorreoLocalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=255)),
            ],
            options={
                'verbose_name': 'Correo Localidad',
                'db_table': 'oeu"."correo_localidad',
                'verbose_name_plural': 'Correos Localidad',
            },
        ),
        migrations.CreateModel(
            name='DisciplinaDeportiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Disciplina Deportiva',
                'db_table': 'oeu"."disciplina_deportiva',
                'verbose_name_plural': 'Disciplinas Deportivas',
            },
        ),
        migrations.CreateModel(
            name='DisciplinaDeportivaLocalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telefono', models.CharField(max_length=19)),
                ('disciplina_deportiva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.DisciplinaDeportiva')),
            ],
            options={
                'verbose_name': 'Disciplina Deportiva',
                'db_table': 'oeu"."disciplina_deportiva_localidad',
                'verbose_name_plural': 'Disciplinas Deportivas',
            },
        ),
        migrations.CreateModel(
            name='GrupoCarrera',
            fields=[
                ('id_grupo_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grupo_carrera', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'oeu"."grupo_carrera',
            },
        ),
        migrations.CreateModel(
            name='GrupoRamaEducacion',
            fields=[
                ('id_grupo_rama_educacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grupo_rama_educacion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'oeu"."grupo_rama_educacion',
            },
        ),
        migrations.CreateModel(
            name='Ieu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='ieu_logo/default.png', max_length=255, null=True, upload_to='')),
                ('fachada', models.ImageField(blank=True, default='ieu_fachada/default.png', max_length=255, null=True, upload_to='')),
                ('logo_edit', models.ImageField(blank=True, default='ieu_logo/default.png', max_length=255, null=True, storage=cuenta.libSobreEscribirImagen.SobreEscribirImagen(), upload_to=oeu.models.image_path_logo)),
                ('fachada_edit', models.ImageField(blank=True, default='ieu_fachada/default.png', max_length=255, null=True, storage=cuenta.libSobreEscribirImagen.SobreEscribirImagen(), upload_to=oeu.models.image_path_fachada)),
                ('publicar', models.BooleanField(default=False)),
                ('cod_activacion', models.CharField(blank=True, max_length=9, null=True)),
                ('editor', models.ForeignKey(blank=True, db_column='persona_editor_id', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('institucion_ministerial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='globales.InstitucionMinisterial')),
                ('institucion_ministerial_edit', models.ForeignKey(blank=True, db_column='institucion_ministerial_edit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institucionedit', to='globales.InstitucionMinisterial')),
            ],
            options={
                'ordering': ['institucion_ministerial'],
                'verbose_name': 'Insitución de Educación Universitaria',
                'db_table': 'oeu"."ieu',
                'verbose_name_plural': 'Instituciones de Educación Universitaria',
            },
        ),
        migrations.CreateModel(
            name='IeuRevisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oeu.Ieu')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'oeu"."ieu_revisor',
            },
        ),
        migrations.CreateModel(
            name='IeuRevisorEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oeu.Ieu')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'oeu"."ieu_revisor_edit',
            },
        ),
        migrations.CreateModel(
            name='IeuSfc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oeu.Ieu')),
                ('sfc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeuconfig.SoporteFormalCambio')),
            ],
            options={
                'db_table': 'oeu"."ieu_sfc',
            },
        ),
        migrations.CreateModel(
            name='InstanciaAdministrativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('publicar', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Instancia Administrativa',
                'db_table': 'oeu"."instancia_administrativa',
                'verbose_name_plural': 'Instancias Administrativas',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('web_site', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('centro_poblado', models.CharField(max_length=255)),
                ('coordenada', djgeojson.fields.PointField(blank=True, null=True)),
                ('poligonal', djgeojson.fields.PolygonField(blank=True, null=True)),
                ('fachada', models.ImageField(blank=True, default='localidad_fachada/default.png', max_length=255, null=True, upload_to='')),
                ('nombre_edit', models.CharField(max_length=255)),
                ('web_site_edit', models.CharField(max_length=255)),
                ('direccion_edit', models.TextField()),
                ('centro_poblado_edit', models.CharField(max_length=255)),
                ('coordenada_edit', djgeojson.fields.PointField()),
                ('poligonal_edit', djgeojson.fields.PolygonField()),
                ('fachada_edit', models.ImageField(blank=True, default='localidad_fachada/default.png', max_length=255, null=True, storage=cuenta.libSobreEscribirImagen.SobreEscribirImagen(), upload_to=oeu.models.image_path_localidad)),
                ('publicar', models.BooleanField(default=False)),
                ('cod_activacion', models.CharField(blank=True, max_length=9, null=True)),
                ('editor', models.ForeignKey(blank=True, db_column='persona_editor_id', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oeu_estado_pub', to='globales.Estado')),
                ('estado_edit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oeu_estado_edit', to='globales.Estado')),
                ('ieu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.Ieu')),
                ('ieu_edit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ieu', to='oeu.Ieu')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oeu_municipio_pub', to='globales.Municipio')),
                ('municipio_edit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oeu_municipio_edit', to='globales.Municipio')),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oeu_parroquia_pub', to='globales.Parroquia')),
                ('parroquia_edit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oeu_parroquia_edit', to='globales.Parroquia')),
                ('requisito_ingreso', models.ManyToManyField(blank=True, db_column='id_requisito_ingreso', db_table='oeu"."localidad_requisitos_ingreso', to='oeuconfig.RequisitoIngreso', verbose_name='Requisitos de Ingreso')),
            ],
            options={
                'ordering': ['ieu__institucion_ministerial', 'tipo_localidad', 'nombre'],
                'verbose_name': 'Localidad',
                'db_table': 'oeu"."localidad',
                'verbose_name_plural': 'Localidades',
            },
        ),
        migrations.CreateModel(
            name='LocalidadRevisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oeu.Localidad')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'oeu"."localidad_revisor',
            },
        ),
        migrations.CreateModel(
            name='LocalidadRevisorEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oeu.Localidad')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'oeu"."localidad_revisor_edit',
            },
        ),
        migrations.CreateModel(
            name='LocalidadSfc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oeu.Localidad')),
                ('sfc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeuconfig.SoporteFormalCambio')),
            ],
            options={
                'db_table': 'oeu"."localidad_sfc',
            },
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Régimen de Estudio',
                'db_table': 'oeu"."modalidad',
                'verbose_name_plural': 'Regímenes de Estudio',
            },
        ),
        migrations.CreateModel(
            name='ModeloPrueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poligonal_edit', djgeojson.fields.PolygonField(null=True)),
                ('coordenada_edit', djgeojson.fields.PointField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizacionEstudiantil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Organizacion Estudiantil',
                'db_table': 'oeu"."organizacion_estudiantil',
                'verbose_name_plural': 'Organizaciones Estudiantiles',
            },
        ),
        migrations.CreateModel(
            name='OrganizacionEstudiantilLocalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telefono', models.CharField(max_length=19)),
                ('instancia_administrativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.InstanciaAdministrativa')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.Localidad')),
                ('organizacion_estudiantil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.OrganizacionEstudiantil')),
            ],
            options={
                'verbose_name': 'Organizacion Estudiantil',
                'db_table': 'oeu"."organizacion_estudiantil_localidad',
                'verbose_name_plural': 'Organizaciones Estudiantiles',
            },
        ),
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Red Social',
                'db_table': 'oeu"."red_social',
                'verbose_name_plural': 'Redes Sociales',
            },
        ),
        migrations.CreateModel(
            name='RedSocialLocalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=255)),
                ('instancia_administrativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.InstanciaAdministrativa')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.Localidad')),
                ('red_social', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.RedSocial')),
            ],
            options={
                'verbose_name': 'Red Social',
                'db_table': 'oeu"."red_social_localidad',
                'verbose_name_plural': 'Redes Sociales',
            },
        ),
        migrations.CreateModel(
            name='SubAreaConocimiento',
            fields=[
                ('id_sub_area_conocimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_subarea_conocimiento', models.CharField(db_column='nombre_area_conocimiento', max_length=255)),
                ('id_area_conocimiento', models.ForeignKey(db_column='id_area_conocimiento', on_delete=django.db.models.deletion.PROTECT, related_name='areaConocimiento4', to='oeu.AreaConocimiento', verbose_name='Área de conocimiento')),
            ],
            options={
                'ordering': ['nombre_subarea_conocimiento'],
                'verbose_name': 'Sub Área de Conocimiento',
                'db_table': 'oeu"."sub_area_conocimiento',
                'verbose_name_plural': 'Sub Áreas de Conocimiento',
            },
        ),
        migrations.CreateModel(
            name='SubTipoInstitucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('orden', models.SmallIntegerField()),
                ('nombre_edit', models.CharField(blank=True, max_length=255, null=True)),
                ('orden_edit', models.SmallIntegerField()),
                ('publicar', models.BooleanField(default=False)),
                ('cod_activacion', models.CharField(blank=True, max_length=9, null=True)),
                ('editor', models.ForeignKey(blank=True, db_column='persona_editor_id', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Sub Tipo IEU',
                'db_table': 'oeu"."sub_tipo_ieu',
                'verbose_name_plural': 'Sub Tipos IEU',
            },
        ),
        migrations.CreateModel(
            name='SubTipoInstitucionRevisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sub_tipo_ieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oeu.SubTipoInstitucion')),
            ],
            options={
                'db_table': 'oeu"."sub_tipo_ieu_revisor',
            },
        ),
        migrations.CreateModel(
            name='SubTipoInstitucionRevisorEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sub_tipo_ieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oeu.SubTipoInstitucion')),
            ],
            options={
                'db_table': 'oeu"."sub_tipo_ieu_revisor_edit',
            },
        ),
        migrations.CreateModel(
            name='SubTipoInstitucionSfc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeuconfig.SoporteFormalCambio')),
                ('sub_tipo_ieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oeu.SubTipoInstitucion')),
            ],
            options={
                'db_table': 'oeu"."sub_tipo_ieu_sfc',
            },
        ),
        migrations.CreateModel(
            name='TelefonoLocalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telefono', models.CharField(max_length=19)),
                ('instancia_administrativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.InstanciaAdministrativa')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.Localidad')),
            ],
            options={
                'verbose_name': 'Teléfono Localidad',
                'db_table': 'oeu"."telefono_localidad',
                'verbose_name_plural': 'Teléfonos Localidad',
            },
        ),
        migrations.CreateModel(
            name='TipoCarrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Programa Académico',
                'db_table': 'oeu"."tipo_carrera',
                'verbose_name_plural': 'Tipos de Programa Académico',
            },
        ),
        migrations.CreateModel(
            name='TipoEspecificoIeuRevisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'oeu"."tipo_especifico_ieu_revisor',
            },
        ),
        migrations.CreateModel(
            name='TipoEspecificoIeuRevisorEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'oeu"."tipo_especifico_ieu_revisor_edit',
            },
        ),
        migrations.CreateModel(
            name='TipoEspecificoIeuSfc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeuconfig.SoporteFormalCambio')),
            ],
            options={
                'db_table': 'oeu"."tipo_especifico_ieu_sfc',
            },
        ),
        migrations.CreateModel(
            name='TipoEspecificoInstitucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('orden', models.SmallIntegerField(verbose_name='Orden')),
                ('nombre_edit', models.CharField(blank=True, max_length=255, null=True)),
                ('orden_edit', models.SmallIntegerField()),
                ('publicar', models.BooleanField(default=False)),
                ('cod_activacion', models.CharField(blank=True, max_length=9, null=True)),
                ('editor', models.ForeignKey(blank=True, db_column='persona_editor_id', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('revisor', models.ManyToManyField(related_name='revisores_tipo_especifico_publicados', through='oeu.TipoEspecificoIeuRevisor', to=settings.AUTH_USER_MODEL)),
                ('revisor_edit', models.ManyToManyField(related_name='revisores_t_e_edit', through='oeu.TipoEspecificoIeuRevisorEdit', to=settings.AUTH_USER_MODEL)),
                ('sfc', models.ManyToManyField(through='oeu.TipoEspecificoIeuSfc', to='oeuconfig.SoporteFormalCambio')),
                ('sub_tipo_ieu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.SubTipoInstitucion')),
                ('sub_tipo_ieu_edit', models.ForeignKey(blank=True, db_column='sub_tipo_ieu_edit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oeutipoieuespecifico', to='oeu.SubTipoInstitucion')),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Tipo IEU Específico',
                'db_table': 'oeu"."tipo_especifico_ieu',
                'verbose_name_plural': 'Tipos IEU Específicos',
            },
        ),
        migrations.CreateModel(
            name='TipoInstitucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.SmallIntegerField()),
                ('nombre_edit', models.CharField(max_length=100)),
                ('orden_edit', models.SmallIntegerField()),
                ('publicar', models.BooleanField(default=False)),
                ('cod_activacion', models.CharField(blank=True, default='00000001', max_length=9, null=True)),
                ('editor', models.ForeignKey(blank=True, db_column='persona_editor_id', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Tipo IEU',
                'db_table': 'oeu"."tipo_ieu',
                'verbose_name_plural': 'Tipos IEU',
            },
        ),
        migrations.CreateModel(
            name='TipoInstitucionRevisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tipo_ieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oeu.TipoInstitucion')),
            ],
            options={
                'db_table': 'oeu"."tipo_ieu_revisor',
            },
        ),
        migrations.CreateModel(
            name='TipoInstitucionRevisorEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tipo_ieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oeu.TipoInstitucion')),
            ],
            options={
                'db_table': 'oeu"."tipo_ieu_revisor_edit',
            },
        ),
        migrations.CreateModel(
            name='TipoInstitucionSfc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeuconfig.SoporteFormalCambio')),
                ('tipo_ieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oeu.TipoInstitucion')),
            ],
            options={
                'db_table': 'oeu"."tipo_ieu_sfc',
            },
        ),
        migrations.CreateModel(
            name='TipoLocalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de localidad',
                'db_table': 'oeu"."tipo_localidad',
                'verbose_name_plural': 'Tipos de localidad',
            },
        ),
        migrations.CreateModel(
            name='TipoTurnoDeEstudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Turno de Estudio',
                'db_table': 'oeu"."turno',
                'verbose_name_plural': 'Turnos de Estudio',
            },
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Título',
                'db_table': 'oeu"."titulo',
                'verbose_name_plural': 'Títulos',
            },
        ),
        migrations.AddField(
            model_name='tipoinstitucion',
            name='revisor',
            field=models.ManyToManyField(related_name='revisores_tipo_publicados', through='oeu.TipoInstitucionRevisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipoinstitucion',
            name='revisor_edit',
            field=models.ManyToManyField(related_name='revisores_tipo_editando', through='oeu.TipoInstitucionRevisorEdit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipoinstitucion',
            name='sfc',
            field=models.ManyToManyField(through='oeu.TipoInstitucionSfc', to='oeuconfig.SoporteFormalCambio'),
        ),
        migrations.AddField(
            model_name='tipoespecificoinstitucion',
            name='tipo_ieu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.TipoInstitucion'),
        ),
        migrations.AddField(
            model_name='tipoespecificoinstitucion',
            name='tipo_ieu_edit',
            field=models.ForeignKey(blank=True, db_column='tipo_ieu_edit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo_ieu_espec', to='oeu.TipoInstitucion'),
        ),
        migrations.AddField(
            model_name='tipoespecificoieusfc',
            name='tipo_especifico_ieu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oeu.TipoEspecificoInstitucion'),
        ),
        migrations.AddField(
            model_name='tipoespecificoieurevisoredit',
            name='tipo_especifico_ieu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oeu.TipoEspecificoInstitucion'),
        ),
        migrations.AddField(
            model_name='tipoespecificoieurevisor',
            name='tipo_especifico_ieu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oeu.TipoEspecificoInstitucion'),
        ),
        migrations.AddField(
            model_name='subtipoinstitucion',
            name='revisor',
            field=models.ManyToManyField(related_name='revisores_sub_tipo_publicados', through='oeu.SubTipoInstitucionRevisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subtipoinstitucion',
            name='revisor_edit',
            field=models.ManyToManyField(related_name='revisores_sub_tipo_editados', through='oeu.SubTipoInstitucionRevisorEdit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subtipoinstitucion',
            name='sfc',
            field=models.ManyToManyField(through='oeu.SubTipoInstitucionSfc', to='oeuconfig.SoporteFormalCambio'),
        ),
        migrations.AddField(
            model_name='subtipoinstitucion',
            name='tipo_ieu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.TipoInstitucion'),
        ),
        migrations.AddField(
            model_name='subtipoinstitucion',
            name='tipo_ieu_edit',
            field=models.ForeignKey(blank=True, db_column='tipo_ieu_edit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oeutipoieu1', to='oeu.TipoInstitucion'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='revisor',
            field=models.ManyToManyField(related_name='revisor_local_publicado', through='oeu.LocalidadRevisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='localidad',
            name='revisor_edit',
            field=models.ManyToManyField(related_name='revisores_local_edit', through='oeu.LocalidadRevisorEdit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='localidad',
            name='servicio',
            field=models.ManyToManyField(blank=True, db_column='id_servicio', db_table='oeu"."localidad_servicio', to='oeuconfig.Servicio', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='sfc',
            field=models.ManyToManyField(through='oeu.LocalidadSfc', to='oeuconfig.SoporteFormalCambio'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='tipo_localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.TipoLocalidad'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='tipo_localidad_edit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipoLocalidad', to='oeu.TipoLocalidad'),
        ),
        migrations.AddField(
            model_name='ieu',
            name='localidad_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='localidades', to='oeu.Localidad'),
        ),
        migrations.AddField(
            model_name='ieu',
            name='localidad_principal_edit',
            field=models.ForeignKey(blank=True, db_column='localidad_principal_edit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_ppal_edi', to='oeu.Localidad'),
        ),
        migrations.AddField(
            model_name='ieu',
            name='revisor',
            field=models.ManyToManyField(related_name='revisor_ieu_publicado', through='oeu.IeuRevisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ieu',
            name='revisor_edit',
            field=models.ManyToManyField(related_name='revisores_ieu_edit', through='oeu.IeuRevisorEdit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ieu',
            name='sfc',
            field=models.ManyToManyField(through='oeu.IeuSfc', to='oeuconfig.SoporteFormalCambio'),
        ),
        migrations.AddField(
            model_name='ieu',
            name='sub_tipo_ieu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.SubTipoInstitucion'),
        ),
        migrations.AddField(
            model_name='ieu',
            name='sub_tipo_ieu_edit',
            field=models.ForeignKey(blank=True, db_column='sub_tipo_ieu_edit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sutipedi', to='oeu.SubTipoInstitucion'),
        ),
        migrations.AddField(
            model_name='ieu',
            name='tipo_especifico_ieu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.TipoEspecificoInstitucion'),
        ),
        migrations.AddField(
            model_name='ieu',
            name='tipo_especifico_ieu_edit',
            field=models.ForeignKey(blank=True, db_column='tipo_especifico_ieu_edit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oeutipoespecificoedit', to='oeu.TipoEspecificoInstitucion'),
        ),
        migrations.AddField(
            model_name='ieu',
            name='tipo_ieu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.TipoInstitucion'),
        ),
        migrations.AddField(
            model_name='ieu',
            name='tipo_ieu_edit',
            field=models.ForeignKey(blank=True, db_column='tipo_ieu_edit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipoInstitucionEdit', to='oeu.TipoInstitucion'),
        ),
        migrations.AddField(
            model_name='disciplinadeportivalocalidad',
            name='instancia_administrativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.InstanciaAdministrativa'),
        ),
        migrations.AddField(
            model_name='disciplinadeportivalocalidad',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.Localidad'),
        ),
        migrations.AddField(
            model_name='correolocalidad',
            name='instancia_administrativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.InstanciaAdministrativa'),
        ),
        migrations.AddField(
            model_name='correolocalidad',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.Localidad'),
        ),
        migrations.AddField(
            model_name='cinefcampodetallado',
            name='id_cine_f_campo_especifico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.CineFCampoEspecifico'),
        ),
        migrations.AddField(
            model_name='carreragruporamaeducaion',
            name='grupo_rama_educacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.GrupoRamaEducacion'),
        ),
        migrations.AddField(
            model_name='carreragrupocarrera',
            name='grupo_carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.GrupoCarrera'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='cine_f_campo_amplio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CineFCampoAmplio2', to='oeu.CineFCampoAmplio'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='cine_f_campo_amplio_edit',
            field=models.ForeignKey(db_column='cine_f_campo_amplio_edit', on_delete=django.db.models.deletion.PROTECT, related_name='CineFCampoAmplio3', to='oeu.CineFCampoAmplio'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='cine_f_campo_detallado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CineFCampoDetallado2', to='oeu.CineFCampoDetallado'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='cine_f_campo_detallado_edit',
            field=models.ForeignKey(db_column='cine_f_campo_detallado_edit', on_delete=django.db.models.deletion.PROTECT, related_name='CineFCampoDetallado3', to='oeu.CineFCampoDetallado'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='cine_f_campo_especifico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CineFCampoEspecifico2', to='oeu.CineFCampoEspecifico'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='cine_f_campo_especifico_edit',
            field=models.ForeignKey(db_column='cine_f_campo_especifico_edit', on_delete=django.db.models.deletion.PROTECT, related_name='CineFCampoEspecifico3', to='oeu.CineFCampoEspecifico'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='ieu_acreditadora_edit',
            field=models.ForeignKey(db_column='ieu_acreditadora_edit', on_delete=django.db.models.deletion.PROTECT, related_name='institucionAcreditadora', to='oeu.Ieu'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='institucion_acreditadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='oeu.Ieu'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.Localidad'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='localidad_edit',
            field=models.ForeignKey(db_column='localidad_edit', on_delete=django.db.models.deletion.PROTECT, related_name='localidad_edit', to='oeu.Localidad'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.Modalidad'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='modalidad_edit',
            field=models.ForeignKey(db_column='modalidad_edit', on_delete=django.db.models.deletion.PROTECT, related_name='modalidad', to='oeu.Modalidad'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='sub_area_conocimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SubAreaConocimiento2', to='oeu.SubAreaConocimiento'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='sub_area_conocimiento_edit',
            field=models.ForeignKey(db_column='sub_area_conocimiento_edit', on_delete=django.db.models.deletion.PROTECT, related_name='SubAreaConocimiento3', to='oeu.SubAreaConocimiento'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='tipo_carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_carreras', to='oeu.TipoCarrera'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='tipo_carrera_edit',
            field=models.ForeignKey(db_column='tipo_carrera_edit', on_delete=django.db.models.deletion.PROTECT, to='oeu.TipoCarrera'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.Titulo'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='titulo_edit',
            field=models.ForeignKey(db_column='titulo_edit', on_delete=django.db.models.deletion.PROTECT, related_name='titulo', to='oeu.Titulo'),
        ),
        migrations.AddField(
            model_name='ayudaeconomicalocalidad',
            name='instancia_administrativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.InstanciaAdministrativa'),
        ),
        migrations.AddField(
            model_name='ayudaeconomicalocalidad',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.Localidad'),
        ),
        migrations.AddField(
            model_name='agrupacioncivicalocalidad',
            name='instancia_administrativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.InstanciaAdministrativa'),
        ),
        migrations.AddField(
            model_name='agrupacioncivicalocalidad',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.Localidad'),
        ),
        migrations.AddField(
            model_name='actividadculturallocalidad',
            name='instancia_administrativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.InstanciaAdministrativa'),
        ),
        migrations.AddField(
            model_name='actividadculturallocalidad',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oeu.Localidad'),
        ),
    ]
